-- Created by %CREATORUSERNAME% <-- your username will be subbed in here.

--[[

	Code you write in this script will be what new LocalScripts you create contain by default.
	When you're finished editing, close this script and changes will apply.
	To change the default script contents later simply select "Custom" in the default local script contents setting again.
	
	Also, remember to delete this comment or it will be in every new script you create from now on.
	
]]

print("Hello world!")